### ISSUE TITLE
Facilities with wrong coordinates

### ISSUE THREAD

**Issue by priisager1** [eea/eprtr2#17] opened 2015-03-23 09:59 UTC
There are many Facilities with incorrect coordinates outside Europe (for example at 0,0). These Facilities should not be shown on map - The problem may relate to the data being confidential and therefore having coordinates set to 0,0.

**Comment by priisager1** [comment] 2015-04-10 14:12
Daniel will discuss this issue with Søren Roug. 
Possible solutions:
- Make sure that only non-confidential Facilitis are shown on map.
- Check other out-of-Europe data and see if there is a common reason for the error in coordinates.

**Comment by alvardan** [comment] 2015-04-13 07:59
Update:

1) The issue is related to a data provider (Member State) using a wrong reference system. The issue is being looked at by the relevant department at EEA and will be fixed as soon as feasible.

2) The department responsible at EEA is IDM3 - contact person Jan Bliki. This does not fall, therefore, under Søren's responsibility.

3) There is a procedure in place to flag and disregard coordinates outside Europe and outermost regions - apparently the procedure was not followed in the last import of data by a contractor - this is being looked at as well as data will be updated in the coming two weeks.

**Comment by mhjelmsmark** [comment] 2015-04-27 07:23
Sounds good

**Closed as completed by mhjelmsmark** 2015-04-27 07:23 UTC
Labels: bug
